name: hotnchill
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  curved_navigation_bar: ^1.0.6
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  fluttertoast: ^8.2.12
  another_flushbar: ^1.12.30
  provider: ^6.0.5
  firebase_app_check: ^0.3.2+4
  connectivity_plus: ^6.1.3
  random_string: ^2.3.1
  image_picker: ^1.0.7
  http: ^1.4.0
  shimmer: ^3.0.0
  http_parser: ^4.1.2
  dio: ^5.8.0+1
  shared_preferences: ^2.2.2
  flutter_stripe: ^11.5.0 # Ensure you're using the correct version
  flutter_dotenv: ^5.2.1
  device_info_plus: ^11.4.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/ice-cream.png
    - assets/images/burger.png
    - assets/images/pizza.png
    - assets/images/salad.png
    - assets/images/Salad.jpg
    - assets/images/Delivery2.jpg
    - assets/images/Delivery3.jpg
    - assets/images/Wallet.png
    - assets/images/chicken.png
    - assets/images/mypizza.jpg
    - assets/images/Mehran.png
    - assets/images/screen1.jpg
    - assets/images/screen2.jpg
    - assets/images/screen3.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf

    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

    - family: Nunito
      fonts:
        - asset: fonts/Nunito-VariableFont_wght.ttf
        - asset: fonts/Nunito-Italic-VariableFont_wght.ttf
          style: italic
